# Generated by Django 4.1.2 on 2022-12-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
