# Generated by Django 4.1.2 on 2022-12-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0005_alter_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
