# Generated by Django 4.1.2 on 2022-12-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='content',
        ),
    ]
